# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests and linter!
      - run: yarn test-coverage
      - run: yarn lint
      - run: yarn build

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker build -t g2pdes/timeline:latest .
      - run: docker tag g2pdes/timeline:latest registry.heroku.com/$HEROKU_APP_NAME/web
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push g2pdes/timeline:latest
      - run: docker login -u $HEROKU_USERNAME -p $HEROKU_PASSWORD registry.heroku.com
      - run: docker push registry.heroku.com/$HEROKU_APP_NAME/web
  
      # install heroku CLI
      - run: wget -qO- https://toolbelt.heroku.com/install.sh | sh
      # login to docker registries (dockerhub + heroku)
  

